package model;
// Generated Jan 24, 2017 3:08:17 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AttributeListRule generated by hbm2java
 */
public class AttributeListRule  implements java.io.Serializable {


     private long id;
     private String listType;
     private Set attributeListRuleItems = new HashSet(0);

    public AttributeListRule() {
    }

	
    public AttributeListRule(long id, String listType) {
        this.id = id;
        this.listType = listType;
    }
    public AttributeListRule(long id, String listType, Set attributeListRuleItems) {
       this.id = id;
       this.listType = listType;
       this.attributeListRuleItems = attributeListRuleItems;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getListType() {
        return this.listType;
    }
    
    public void setListType(String listType) {
        this.listType = listType;
    }
    public Set getAttributeListRuleItems() {
        return this.attributeListRuleItems;
    }
    
    public void setAttributeListRuleItems(Set attributeListRuleItems) {
        this.attributeListRuleItems = attributeListRuleItems;
    }




}


