package model;
// Generated Jan 24, 2017 3:08:17 PM by Hibernate Tools 4.3.1



/**
 * AttributeRangeRule generated by hbm2java
 */
public class AttributeRangeRule  implements java.io.Serializable {


     private long id;
     private String min;
     private String max;
     private String rangeType;

    public AttributeRangeRule() {
    }

    public AttributeRangeRule(long id, String min, String max, String rangeType) {
       this.id = id;
       this.min = min;
       this.max = max;
       this.rangeType = rangeType;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getMin() {
        return this.min;
    }
    
    public void setMin(String min) {
        this.min = min;
    }
    public String getMax() {
        return this.max;
    }
    
    public void setMax(String max) {
        this.max = max;
    }
    public String getRangeType() {
        return this.rangeType;
    }
    
    public void setRangeType(String rangeType) {
        this.rangeType = rangeType;
    }




}


