package model;
// Generated Jan 24, 2017 3:08:17 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * BusinessRule generated by hbm2java
 */
public class BusinessRule  implements java.io.Serializable {


     private long id;
     private Project project;
     private BusinessRuleType businessRuleType;
     private String name;
     private String errorMessage;
     private String tableName;
     private String columnName;
     private String columnType;
     private Date createdOn;

    public BusinessRule() {
    }

    public BusinessRule(long id, Project project, BusinessRuleType businessRuleType, String name, String errorMessage, String tableName, String columnName, String columnType, Date createdOn) {
       this.id = id;
       this.project = project;
       this.businessRuleType = businessRuleType;
       this.name = name;
       this.errorMessage = errorMessage;
       this.tableName = tableName;
       this.columnName = columnName;
       this.columnType = columnType;
       this.createdOn = createdOn;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    public BusinessRuleType getBusinessRuleType() {
        return this.businessRuleType;
    }
    
    public void setBusinessRuleType(BusinessRuleType businessRuleType) {
        this.businessRuleType = businessRuleType;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getErrorMessage() {
        return this.errorMessage;
    }
    
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
    public String getColumnName() {
        return this.columnName;
    }
    
    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }
    public String getColumnType() {
        return this.columnType;
    }
    
    public void setColumnType(String columnType) {
        this.columnType = columnType;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }




}


