package model;
// Generated Jan 24, 2017 3:08:17 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class CategoryModel implements java.io.Serializable {

    private long id;
    private String name;
    private Set businessRuleTypes = new HashSet(0);

    public CategoryModel() {
    }

    public CategoryModel(long id, String name) {
        this.id = id;
        this.name = name;
    }

    public CategoryModel(long id, String name, Set businessRuleTypes) {
        this.id = id;
        this.name = name;
        this.businessRuleTypes = businessRuleTypes;
    }

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Set getBusinessRuleTypes() {
        return this.businessRuleTypes;
    }

    public void setBusinessRuleTypes(Set businessRuleTypes) {
        this.businessRuleTypes = businessRuleTypes;
    }

}
