package model;
// Generated Jan 24, 2017 3:08:17 PM by Hibernate Tools 4.3.1



/**
 * OtherRule generated by hbm2java
 */
public class OtherRuleModel  implements java.io.Serializable {


     private long id;
     private String sqlCode;
     private String typeRule;

    public OtherRuleModel() {
    }

    public OtherRuleModel(long id, String sqlCode, String typeRule) {
       this.id = id;
       this.sqlCode = sqlCode;
       this.typeRule = typeRule;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getSqlCode() {
        return this.sqlCode;
    }
    
    public void setSqlCode(String sqlCode) {
        this.sqlCode = sqlCode;
    }
    public String getTypeRule() {
        return this.typeRule;
    }
    
    public void setTypeRule(String typeRule) {
        this.typeRule = typeRule;
    }




}


