package model;
// Generated Jan 24, 2017 3:08:17 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class RoleModel  implements java.io.Serializable {


     private long id;
     private String name;
     private Set users = new HashSet(0);

    public RoleModel() {
    }

	
    public RoleModel(long id, String name) {
        this.id = id;
        this.name = name;
    }
    public RoleModel(long id, String name, Set users) {
       this.id = id;
       this.name = name;
       this.users = users;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


