package model;
// Generated Jan 24, 2017 3:08:17 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class UserModel implements java.io.Serializable {

    private long id;
    private RoleModel role;
    private String username;
    private String password;
    private Set projects = new HashSet(0);

    public UserModel() {
    }

    public UserModel(long id, RoleModel role, String username, String password) {
        this.id = id;
        this.role = role;
        this.username = username;
        this.password = password;
    }

    public UserModel(long id, RoleModel role, String username, String password, Set projects) {
        this.id = id;
        this.role = role;
        this.username = username;
        this.password = password;
        this.projects = projects;
    }

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public RoleModel getRole() {
        return this.role;
    }

    public void setRole(RoleModel role) {
        this.role = role;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Set getProjects() {
        return this.projects;
    }

    public void setProjects(Set projects) {
        this.projects = projects;
    }

}
