package model;
// Generated Feb 1, 2017 1:00:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class UserModel  implements java.io.Serializable {


     private long id;
     private RoleModel role;
     private String username;
     private String password;
     private Set userHasProjects = new HashSet(0);

    public UserModel() {
    }

	
    public UserModel(long id,RoleModel role, String username, String password) {
        this.id = id;
        this.role = role;
        this.username = username;
        this.password = password;
    }
    public UserModel(long id,RoleModel role, String username, String password, Set userHasProjects) {
       this.id = id;
       this.role = role;
       this.username = username;
       this.password = password;
       this.userHasProjects = userHasProjects;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public RoleModel getRole() {
        return this.role;
    }
    
    public void setRole(RoleModel role) {
        this.role = role;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getUserHasProjects() {
        return this.userHasProjects;
    }
    
    public void setUserHasProjects(Set userHasProjects) {
        this.userHasProjects = userHasProjects;
    }

    @Override
    public String toString() {
        return "UserModel{" + "id=" + id + ", role=" + role + ", username=" + username + ", password=" + password + ", userHasProjects=" + userHasProjects + '}';
    }


}


