package model;
// Generated Feb 1, 2017 1:00:28 PM by Hibernate Tools 4.3.1



/**
 * UserHasProjectId generated by hbm2java
 */
public class UserHasProjectIdModel  implements java.io.Serializable {


     private long projectId;
     private long userId;

    public UserHasProjectIdModel() {
    }

    public UserHasProjectIdModel(long projectId, long userId) {
       this.projectId = projectId;
       this.userId = userId;
    }
   
    public long getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(long projectId) {
        this.projectId = projectId;
    }
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserHasProjectIdModel) ) return false;
		 UserHasProjectIdModel castOther = ( UserHasProjectIdModel ) other; 
         
		 return (this.getProjectId()==castOther.getProjectId())
 && (this.getUserId()==castOther.getUserId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getProjectId();
         result = 37 * result + (int) this.getUserId();
         return result;
   }   

    @Override
    public String toString() {
        return "UserHasProjectIdModel{" + "projectId=" + projectId + ", userId=" + userId + '}';
    }

   
}


